### ISSUE TITLE
Offer more dynamic approach for using MSDKUITheme

### ISSUE THREAD

**Issue by william-reed** [heremaps/msdkui-android#154]
The user guide doesn't make any mention of needing to use the `MSDKUIDarkTheme`. The quick start guide does however (also exemplified by the example projects).

It would be useful to explain this in the user guide and offer a more dynamic approach to getting this theme in use. For example my application uses a base theme which is not mapped to the same as what the `MSDKUIDarkTheme` is based on. I wound up using the following extension functions to avoid needing to deal with that issue:

```
/**
 * [LayoutInflater.inflate], but uses a ContextThemeWrapper to apply the HERE theme to it
 */
internal fun LayoutInflater.inflateWithHereTheme(
    @LayoutRes resource: Int,
    root: ViewGroup?,
    attachToRoot: Boolean
): View {
    val contextThemeWrapper = ContextThemeWrapper(context, R.style.MSDKUIDarkTheme)
    // clone the inflater using the ContextThemeWrapper
    val localInflater = cloneInContext(contextThemeWrapper)
    // inflate the layout using the cloned inflater, not default inflater
    return localInflater.inflate(resource, root, attachToRoot)
}

internal fun Context.wrapWithHereTheme() = ContextThemeWrapper(this, R.style.MSDKUIDarkTheme)
```
It would be useful to offer something like this out of the box or some other way to avoid having to change the entire applications theme.

**Comment by tstaszak89** [comment]
First of all this is an ui kit so styling is one of the main functionalities of this library, so your application must use `MSDKUIDarkTheme`, I'm afraid that I can't see a simplier solution for this, but you can fully modify `MSDKUIDarkTheme` style. Take a look into MSDKUIDev project to see examples of how to modify the style of ui kit components.

Additionally if you want to change parent theme of the `MSDKUIDarkTheme` you can add MSDKUIKit into your project as source code, instead of the .aar file (instructions are here: https://github.com/heremaps/msdkui-android/blob/master/Documentation/Guides/ContributionGuide.md#optional-building-the-here-ui-kit-library-and-the-demo-as-part-of-one-project), and next modify `<style name="MSDKUIDarkTheme" parent="Theme.AppCompat.Light.DarkActionBar">` line in that file: /MSDKUILib/src/main/res/values/style.xml

**Comment by william-reed** [comment]
I still stand by the point that my above snippet seems to be the simplest way to achieve what I want rather than adding the entire project. I just think it may be useful to include something about that in the user guide

**Comment by datasun** [comment]
As you wrote above, theme setup is already explained in the [quick start](https://github.com/heremaps/msdkui-android/blob/master/Documentation/Guides/QuickStart.md#theme-setup) and [contribution](https://github.com/heremaps/msdkui-android/blob/master/Documentation/Guides/ContributionGuide.md#optional-building-the-here-ui-kit-library-and-the-demo-as-part-of-one-project) guides. This should provide enough help for any Android developer to get started. Any additional customization does not require specific MSDKUI knowledge and is covered [here](https://developer.android.com/guide/topics/ui/look-and-feel/themes).
