### ISSUE TITLE
UnitSystem.IMPERIAL_UK and UnitSystem.IMPERIAL_US are not handled correctly

### ISSUE THREAD

**Issue by agap** [heremaps/msdkui-android#196]
When I apply `UnitSystem.IMPERIAL_US` on `GuidanceManeuverView` (I haven't checked other views), the distances are shown in yards/miles. If I change it to `UnitSystem.IMPERIAL_UK`, the distances are shown in feet/miles. 

I think it should be the other way around - feet are from the US unit system, while yards are from UK's unit system.

**Comment by stefan-troyke** [comment]
We will check this

**Comment by tstaszak89** [comment]
Distance units across the globe is quite diverse topic so we had to decide on something. We assigned typical distance units pairs: imperial US to yards/miles, imperial UK to feet/miles, metric to meters/kilometres. Everything works as intended.

If you want to use other distance units pairs then you should clone this repository and add it to your project as source code rather than aar library. Next you can modify `msdkui-android/MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/common/DistanceFormatterUtil.java` and `msdkui-android/MSDKUIKit/MSDKUILib/src/main/java/com/here/msdkui/common/SpeedFormatterUtil.java` to achieve any kind of unit combination that you like.
